services:
    app:
        image: us-docker.pkg.dev/aldinger-426410/docker-1/aldinger-netsuite-backend
        build: .
        volumes:
            - ./${GOOGLE_APPLICATION_CREDENTIALS}:/tmp/{GOOGLE_APPLICATION_CREDENTIALS}
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: /tmp/{GOOGLE_APPLICATION_CREDENTIALS}
            K_SERVICE: dev
            K_CONFIGURATION: dev
            K_REVISION: dev-00001
            PUBLIC_URL: ${PUBLIC_URL}
        env_file: .env
        ports:
            - 8080:8080
